{{- if .Values.components.flowAutomation.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dataflow.flowAutomation.fullname" . }}-ca
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "dataflow.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "dataflow.flowAutomation.fullname" . }}
data:
    # mongo ca 证书
  mongo.ca.pem:  {{ .Values.depServices.mongodb.sslCAFile | quote }}
{{- end }}
